version: '3'
services:
  master:
    image: redis
    container_name: redis-master
    command: redis-server  --requirepass 1234  --masterauth 1234   --replica-announce-ip 192.168.1.102   --replica-announce-port  6380 
    ports:
      - 6380:6379
  slave1:
    image: redis
    container_name: redis-slave-1
    ports:
      - 6381:6379
    command:  redis-server --slaveof redis-master 6379 --masterauth 1234  --requirepass 1234  --replica-announce-ip 192.168.1.102  --replica-announce-port  6381
  slave2:
    image: redis
    container_name: redis-slave-2
    ports:
      - 6382:6379
    command: redis-server --slaveof redis-master 6379 --masterauth 1234 --requirepass 1234  --replica-announce-ip 192.168.1.102  --replica-announce-port  6382
