name = "vitedge-react"
type = "javascript"
account_id = "e1c7bebb78a2bbb5a8630791cf974d8c"
workers_dev = true
compatibility_date = "2021-10-24"

[site]
bucket = "dist/client"
entry-point = "."

[build]
command = ""
watch_dir = "dist/worker"

[build.upload]
format = "service-worker"